### ISSUE TITLE
Having problems changing multiple Views at once

### ISSUE THREAD

**Issue by Powersource** [gyscos/Cursive#102]
I don't know whether it's me or the documentation but I can't seem to solve this in a nice way. See the comments in typed_some() for explanations (please ask if my ramblings are unclear)

```
extern crate cursive;
extern crate rand;

use cursive::Cursive;
use cursive::views::{Dialog, TextView, EditView, LinearLayout};
use cursive::traits::Identifiable;
use cursive::view::Finder;
use rand::Rng;

fn main() {
    // This really messes with stdout. Seems to disable it by default but when
    // siv is running println prints in random places on the screen.
    let mut siv = Cursive::new();
    siv.add_global_callback('q', |s| s.quit());

    let words = Words::new();

    siv.add_layer(Dialog::around(LinearLayout::vertical()
            .child(TextView::new("testtext").with_id("target_field"))
            .child(EditView::new()
                .on_edit(move |s, input, _| typed_some(s, input, &words))
                .with_id("input_field")))
        .title("Keyurses")
        .button("Quit", |s| s.quit()));

    siv.run();
}

fn typed_some(siv: &mut Cursive, input: &str, words: &Words) {
    // This one would be optimal but pisses off the borrow checker about siv
    /*let target_word = siv.find_id::<TextView>("target_field").unwrap();
    let input_word = siv.find_id::<EditView>("input_field").unwrap();
    if target_word.get_content() == input {
        target_word.set_content(words.rand_word());
        input_word.set_content("");
    }*/
    
    // This one doesn't crash but is ugly
    /*let mut reset_input = false;
    {
       let target_word = siv.find_id::<TextView>("target_field").unwrap();
       if target_word.get_content() == input {
           target_word.set_content(words.rand_word());
           reset_input = true;
       }
    }
    if reset_input {
       siv.find_id::<EditView>("input_field").unwrap().set_content("");
    }*/

    // This one crashes due to the last find_id not finding anything. Why?
    // Does it only look for children?
    /*let target_word = siv.find_id::<TextView>("target_field").unwrap();
    if target_word.get_content() == input {
        target_word.set_content(words.rand_word());
        target_word.find_id::<EditView>("input_field")
            .unwrap()
            .set_content("");
    }*/

    // This one works but is verbose
    /*if siv.find_id::<TextView>("target_field").unwrap().get_content() == input {
        siv.find_id::<TextView>("target_field").unwrap().set_content(words.rand_word());
        siv.find_id::<EditView>("input_field")
            .unwrap()
            .set_content("");
    }*/

    // This one feels reasonable but TextView doesn't implement content() (EditView does.
    // Intentional?)
    /*let target_word = siv.find_id::<TextView>("target_field").unwrap();
    if target_word.get_content() == input {
        target_word.content(words.rand_word())
            .find_id::<EditView>("input_field")
            .unwrap()
            .set_content("");
    }*/
}

#[derive(Debug)]
struct Words {
    list: Vec<&'static str>,
}

impl Words {
    fn new() -> Self {
        Words { list: include_str!("google-10000-english-usa.txt").lines().collect() }
    }

    fn rand_word(&self) -> &str {
        let mut rng = rand::thread_rng();
        rng.choose(&self.list).unwrap()
    }
}
```

**Comment by gyscos** [comment]
> TextView doesn't implement content() (EditView does. Intentional?)

`EditView::content` is a "chainable" method to call `EditView::set_content` by taking and returning `self` by value.
`TextView` only has `set_content`, because the constructor already takes the content, so there is little point in setting it in such constructor-chain (I could add it if it was actually needed, but I haven't found a use for it yet).

>  This one crashes due to the last find_id not finding anything. Why? Does it only look for children?
Yes, `find_id` only looks at the subtree (which is the entire tree when you call if from the Cursive root).
Views don't have "up" references to their parent, so they can't reach out this way.

The core issue is that as you noticed, only one view can be worked on at a time. This is partly because when borrowing two views, one could be the parent of the other, and you could get mutable aliasing this way.

**Comment by Powersource** [comment]
Thanks for the clarifications.

I think the documentation for find_id should clarify this.

And aah, content() still wouldn't work here due do the find_id thing.

And yes something to make this simpler would be nice. I ended up going with the brackets solution. I don't mind the verbose solution's repetition of finding, it's just that it's so much repeated code. Some macro (I should really learn how they work) or something would be enough for me.

**Comment by gyscos** [comment]
The `refview` branch changes the way views are accessed:
* `find_id` now takes a closure that is called on the view, if found. The closure can return something, which will be returned in an `Option` by `find_id`.
* `RefCellView` can wrap a view to provide interior mutability: `RefCellView::get_mut` returns a mutable reference, without being tied to the lifetime of the `RefCellView`. You can call that inside `find_id`:
`siv.find_id("refview", RefCellView<EditView>::get_mut)`.
* `find_id_mut` is a shortcut for the above code, looking for a `RefCellView` and returning the reference.

Example usage:
```rust
// ...

            // Use `with_id_mut` to automatically wrap the view 
            // in a `RefCellView` + `IdView`
            .child(EditView::new()
                .on_edit(move |s, input, _| typed_some(s, input, &words))
                .with_id_mut("input_field")))

// ...

let input_word = siv.find_id_mut::<EditView>("input_field").unwrap();
siv.find_id("target_field", |target| {
    if target.get_content() == input {
        target.set_content(words.rand_word());
        input_word.set_content("");
    }
});
```

**Comment by gyscos** [comment]
Unrelated comment regarding `println`: the entire display is going through stdout (with control codes and all), so it's not really available for debugging and the like.

* For debugging (when you don't want to use `gdb`), I usually print to stderr instead (there is a `println_stderr!` macro defined  in `src/lib.rs`, though it's not public) and redirect it to a file when I run the application: `cargo run 2> stderr.txt`, then in another terminal I run `tail -f stderr.txt`. It's also useful to read panics and other messages.

* To just show information to the user, the cursive views have to be used. Cursive is a full-screen terminal UI; if you need something less intrusive, some other libraries may be interesting, like [liner](https://crates.io/crates/liner).

**Comment by Powersource** [comment]
Busy right now, but meaning to get to trying it!

And thanks for the tip about tail -f, I ended up just ending the first command with something like `; less ERR` which had its problems. I would recommend putting this in the documentation even if you could argue it's out of scope.

**Comment by Powersource** [comment]
So [here's the code](https://github.com/Powersource/keyurses/blob/8b801120d4f8e9c0b7b19fd6a7f8482c957a2d93/src/main.rs) with your suggested changes (and some type stuff to satisfy the compiler).

I don't know if I have a proper conclusion, but at least for this case I might want to stick with the old code. It's uglier but less... involved/complex? Might be worth it for larger use cases when the {} approach starts to get really messy. The `with_id_mut` part feels the weirdest. When trying different implementations of typed_some you're going to have to keep an eye on what type of id you're targeting or risk getting runtime panics (when it can't find the id). Idk if this could maybe feel better with different naming? 

I might try `find_id_mut`, would it just be a matter of finding both views and mutating as you wish? Without understanding it fully it sounds like it'd be very prone to panics.

**Comment by gyscos** [comment]
> The with_id_mut part feels the weirdest. When trying different implementations of typed_some you're going to have to keep an eye on what type of id you're targeting or risk getting runtime panics (when it can't find the id).

One good point is that `with_id_mut` sounds like it "implies" `with_id`, and calling `find_id` feels like it *should* work, so that's the first thing I'll work on.

Then, maybe `with_id` doesn't *need* to exist if we can just use `with_id_mut` everywhere?
I feel a bit weird having `RefCell`s everywhere by default, but maybe the performance hit is negligible. On the good side, it would make the API simpler (only one method to give a view an ID), but it still feels a bit ugly. :-/

> I might try find_id_mut, would it just be a matter of finding both views and mutating as you wish? Without understanding it fully it sounds like it'd be very prone to panics.

You could indeed use `with_id_mut` and `find_id_mut` on both views, free to edit them in any order. As long as the views aren't linked (one being the parent of the other) it should be fine.

**Comment by gyscos** [comment]
cb3adc5baf0c7d7b1bf87530bcff93d15d1a72c2 now lets `find_id` access views declared with `with_id_mut`.

This means `with_id` is not necessary anymore, since `with_id_mut` can do everything `with_id` can. I could then remove `with_id`, and rename `with_id_mut` as `with_id`.

I'll probably also want to rename `find_id` and `find_id_mut`, since they differ quite a bit (one runs the given closure, and the other return a handle). Maybe `on_view_id` for the one that takes a closure, and `find_id` for the one that returns a handle...

**Comment by gyscos** [comment]
I finally merged the `refview` branch, and merged `RefCellView` into `IdView`. No more `with_id_mut` or `find_id_mut`.
* Just like before, just use `with_id` on views to make them available.
* `find_id` works like before, but returns a `ViewRef<T>` instead of `&mut T`.
* `call_on_id` takes a closure and runs it on the target view.

**Comment by gyscos** [comment]
I'll assume this is fixed - feel free to open it again if I'm wrong!
