### ISSUE TITLE
Consider making EditView::on_edit take an FnMut

### ISSUE THREAD

**Issue by Powersource** [gyscos/Cursive#108]
Basically this entire Q&A https://stackoverflow.com/questions/41990175/problems-with-mutability-in-a-closure  
user's comment at the bottom sums it up:

> It would still be a good idea to check with the cursive developers whether on_edit really requires a Fn or it could be relaxed to accept a FnMut. If the current constraint is there for a good reason, cheating it with RefCell might eventually lead to a panic at run-time.

**Comment by gyscos** [comment]
`EditView` stores a `Rc<Fn(...)>`, because when runnin, the callback itself can have access to the `EditView`, and change (or call again) the callback. This is the main reason not to store a `FnMut`.

Now, `EditView` could conceivable be modified to store something like a `Rc<RefCell<FnMut(...)>>` to provide the desired mutability. Basically, this means that giving it a callback that looks for the `EditView` itself and runs the callback again (by calling the view's `on_event` method for instance) would panic (well - we could put a check there to see if the callback is already borrowed, and just ignore the event if it is, but that's not a very clean solution and a surprising behavior).

In the end, pushing the `RefCell` to the closure itself is more flexible, and the user is more aware of the exact runtime risks...

That being said, I'm open to a better design allowing for nicer mutability constraints.

**Comment by gyscos** [comment]
I pushed a [`on_edit`](https://github.com/gyscos/Cursive/tree/on_edit ) branch with the "disable" solution (where `RefCell<FnMut>` are stored, and recursive callbacks are "disabled", IE calling `on_event` from the `on_edit` callback will behave as if no `on_edit` was set). You can try it and see if it helps your problem.

**Comment by gyscos** [comment]
I ended up keeping `on_edit` as it was, and adding `as_edit_mut` that calls `on_edit` with:

```rust
let callback = RefCell::new(callback);
move |s, text, cursor| {
    if let Ok(mut callback) = callback.try_borrow_mut() {
        (&mut *callback)(s, text, cursor);
    }
}
```

It ends up being a rather small change and rather isolated from the rest of the code, which would point to it not being necessary in `Cursive` itself; but it's a bit too complex and verbose to force this on users...

Ideally, I'd just add a method like that:

```rust
fn immutablify<Args, F: FnMut<Args>>(f: F) -> impl Fn(Args) {
    let f = RefCell::new(f);
    move |args: Args| {
        if let Ok(f) = f.try_borrow_mut() {
            (&mut *f)(args);
        }
    }
}
```

But:
* This uses "impl trait", which doesn't look stable quite yet
    * This could be worked around by boxing the return - non optimal, but still ok
* This requires some voodoo with the `Args` and `FnMut` traits that I are probably either unstable or plain impossible for now.

**Comment by gyscos** [comment]
It should be in master as of 0bbc10706e501032949b4a131e2e6f1aa562bb7a.

**Comment by legolord208** [comment]
Seems to be the same with `on_submit` and `MenuTree`'s `leaf`.

**Comment by gyscos** [comment]
Ah yes, any place that takes a callback method will need special handling :-/

**Comment by legolord208** [comment]
Oh, ok.

**Comment by gyscos** [comment]
That was one of the main attractive points of a `immutablify` method... I'll see if a `immutablify!` macro would be easier to implement.
