### ISSUE TITLE
Allow for creation of custom events

### ISSUE THREAD

**Issue by dospunk** [gyscos/Cursive#160]
It would be really useful to be able to create custom events that we could trigger from inside the program, rather than from user input

**Comment by punkkeks** [comment]
You can just call `on_event` on any View you like (not on the Cursive struct itself though). What is your desired behavoir? To call on_evnt on the Cursive struct?

**Comment by gyscos** [comment]
I was considering custom events for some backends by adding `Event::Custom(Box<Any>)`; it could be used to inject events manually as well (though manual event injection is not currently well supported, that would be another improvement).

The main thing it allows it to let the layout tree dispatch the event to the selected view, rather than selecting a view directly. I'd love to hear how you plan on using that!

**Comment by dospunk** [comment]
It would just make things a tad cleaner to write I think. I'm currently working on an IRC client just as a fun personal project and every time I want to update the textview with new messages, I have to call it directly like this
```rust
s.call_on_id("feed", |feed: &mut TextView| {
	feed.append_content(buffer.as_ref());
});
```

Which feels a little clunky. I'd love to just be able to pass the text to an event, maybe something like
```rust
fire("new-message-event", buffer)
```

Where `"new-message-event"` refers to an event the same way `"feed"` refers to my textview.

**Comment by gyscos** [comment]
Oh, but then the view would only receive the event if it was in focus; if the user was selecting a button instead, it wouldn't reach the `TextView`.

**Comment by dospunk** [comment]
Ah, makes sense. Good to know thanks!
