### ISSUE TITLE
Possible bug due to order of width and id

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#170]
Given this minimal example:

```
extern crate cursive;

use cursive::Cursive;
use cursive::views::*;
use cursive::traits::{Boxable,Identifiable};

fn main() {
    let mut cur = Cursive::new();

    cur.add_layer(LinearLayout::horizontal()
        .child(Dialog::around(LinearLayout::vertical()
            .child(Checkbox::new().on_change(|cur, val| {
                cur.call_on_id("v1", |cb: &mut EditView| cb.set_enabled(!val));
            }))
            .child(EditView::new().content("0").with_id("v1").fixed_width(5))))
        .child(Dialog::around(LinearLayout::vertical()
            .child(Checkbox::new().on_change(|cur, val| {
                cur.call_on_id("v2", |cb: &mut EditView| cb.set_enabled(!val));
            }))
            .child(EditView::new().content("0").fixed_width(5).with_id("v2"))))
    );
    cur.run();
}
```

V1 works, v2 not and the only difference here is the order on which fixed_width and with_id are provided. I'm not sure what leads to this bug, but I think it should be fixed :)

**Comment by gyscos** [comment]
Ah yes, I think this point needs more documentation.

The problem is caused by the way these methods work: [`with_id`](https://docs.rs/cursive/0.7.4/cursive/view/trait.Identifiable.html#method.with_id) and [`fixed_width`](https://docs.rs/cursive/0.7.4/cursive/view/trait.Boxable.html#method.fixed_width) actually wrap the view (respectively in an [`IdView`](https://docs.rs/cursive/0.7.4/cursive/views/struct.IdView.html) and a [`BoxView`](https://docs.rs/cursive/0.7.4/cursive/views/struct.BoxView.html)).

This means the type of `EditView::new().fixed_width(5)` is not `EditView`, but `BoxView<EditView>`. So when you write `EditView::new().fixed_width(5).with_id("v2")`, the view you can access through the `"v2"` ID is this `BoxView<EditView>`, not the inner `EditView`.

The [3rd tutorial](https://github.com/gyscos/Cursive/blob/master/doc/tutorial_3.md) tries to address this:

```
let select = SelectView::<String>::new()
    .on_submit(on_submit)
    .with_id("select")
    .fixed_size((10, 5));
```
> (Here again, the order is important: we want to wrap the SelectView, not the BoxView. But we still need to call on_submit before that.)

The general idea to order these methods is:
* First, use all methods native to the given view; they usually return the view itself, so within this group, the order doesn't matter.
* Then, `with_id`: when looking up an ID, you want the inner view, not any other wrapper.
* Then, other wrappers, like `fixed_width`.

**Comment by gyscos** [comment]
I updated the doc for `with_id`, and it now mentions this detail.
