### ISSUE TITLE
[usage/design question] how to transfer data outside event?

### ISSUE THREAD

**Issue by xliiv** [gyscos/Cursive#173]
I'd like to do more or less somthing like this:

```rust
extern crate cursive;

use cursive::Cursive;
use cursive::views::{Dialog, ListView};


pub struct App {
    my_data: String,
    cursive: Cursive,
}


impl App {
    pub fn new(cursive: Cursive) -> App {
        // TODO: cursive is optional
        App {
            my_data: String::from(""),
            cursive: cursive,
        }
    }
    pub fn build(&mut self) {
        let list_view = ListView::new();

        self.cursive.add_layer(
            Dialog::new()
                .title("Please fill out this form")
                .button("Ok", |_s| {
                    // using self here invalidates "+ static" bound from: https://docs.rs/cursive/0.7.5/cursive/views/struct.Dialog.html#method.button
                    //self.my_data = String::from("test");
                    //eprintln!("{:?}", x.my_data);
                })
                .content(list_view)
        );
    }

    pub fn show(&mut self) {
        self.cursive.add_global_callback('q', |s| s.quit());
        self.build();
        self.cursive.run();
    }
}


fn main() {
    let mut app = App::new(Cursive::new());
    app.show();
}
```

I'm wondering how can i transfer data from `cursive::Cursive`'s `event` to somewhere else (`App.my_data`).. .

**Comment by gyscos** [comment]
Hi!

As you noticed, views must be `'static`. This means they cannot borrow content from outside (the `Cursive` object is not tied to the lifetime of your `App`). There are a few options to work around this limitation:
* A simple solution for small single-threaded projects is to use the usual `Rc<RefCell>` combo.
```rust
let app = Rc::new(RefCell::new(App::new()));

let btn_app = app.clone();
cursive.add_layer(Dialog::new().button("Ok", move |s| {
    btn_app.borrow_mut().my_data = String::from("test");
}));
```
It does make it a bit trickier to build the UI from `App::build` (since you need a `Rc<RefCell<App>>`, but you only have a `&mut App` here), so you may need to define a new type containing a `Rc<RefCell<App>>`, and build the UI from this type.
Or, you could more finely precise what should be shared, and instead make `App::my_data` itself a `Rc<RefCell<String>>` ; you'd then send a clone of this `Rc` to the closure:
```rust
let app = App::new();

let btn_data = app.my_data.clone();
cursive.add_layer(Dialog::new().button("Ok", move |s| {
    *btn_data.borrow_mut() = String::from("test");
}));
```

* Another popular solution for larger projects (especially when threading is involved, for network/disk operations) is message-passing: you send messages through thread-safe channels, while another thread reads from this channel and performs the desired actions.

**Comment by xliiv** [comment]
Thanks for quick answer.
The `RefCell` in `Rc` solved the problem.
Btw: Great library with great tutorial with great API. I'm impressed :)
