### ISSUE TITLE
Using more references instead of copies

### ISSUE THREAD

**Issue by hellow554** [gyscos/Cursive#174]
I used clippy on the code, because I changed a thing and then I realised that clippy outputs some warnings about using a copy instead of a reference (warning: this argument is passed by value, but not consumed in the function body) in various places, e.g. 

```
warning: this argument is passed by value, but not consumed in the function body
   --> src/views/dialog.rs:223:43
    |
223 |     fn on_event_content(&mut self, event: Event) -> EventResult {
    |                                           ^^^^^
    |
    = note: #[warn(needless_pass_by_value)] on by default
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.176/index.html#needless_pass_by_value
help: consider taking a reference instead
```

I think the fixed and easily be solved.

If we look a little bit further and have a look at the `View` trait we see the function definitons which also takes a copy of Event and Vec2. I don't think that that is necessary and could be changed as well, but that will lead to a breaking change, because we change the public interface of this crate. Is that something to consider for the next big release? Shall I/you/whoever cleanup the "small" issues mentioned above?

**Comment by gyscos** [comment]
Hi!

* The `Vec2` class implements `Copy`, so there's little point in passing it by reference.
* Similarly, the `Event` class *almost* implements `Copy` - i think it used to, but `Event::Unknown` starting including a `Vec<u8>`, at which point I didn't change the API. Still, every other variant implements `Copy`, so cloning an `Event` is almost always a simple memcopy. And yet, I don't think we ever clone an event in the current code base: this model of passing over the event makes sense, even if the methods would work as well with a reference.

Usually, consuming the event in the `on_event` method makes sense - .

In the case of `on_event_content`, it's the same idea: we take on the responsibility of the `on_event` method.

I usually try to follow clippy's recommendations, but I'm a bit torn about this one. As you mentioned, it wouldn't take much to have views take a `&Event` (as I said, `Event` is virtually `Copy`, so taking a reference doesn't prevent anything). It wouldn't be an optimization thing (the compiler is already smart enough to pass references rather than big structs when needed), and it would add a (tiny) bit of trouble to every `on_event` call.

**Comment by hellow554** [comment]
Copy means, there is a memcpy going on which will take time and memory. I totaly undestand your argument, especially with the responsibility thing, but please keep in mind, that a copy is not free think like a reference is.

**Comment by gyscos** [comment]
To be clear, I think this issue is really only about ergonomics.
* The memory/time cost of these is negligible compared to printing anything to the console
* I'm quite confident the compiler in these cases is able to omit most copies and actually pass references instead.

Let's not blindly try to maximize performances without any metric. At this point, usability has a way higher priority than what we could gain here. The question is about what makes the most sense, what feels the most natural.

I feel like the referencing/dereferencing involved would be a small loss of convenience, that no visible gain would offset.
