### ISSUE TITLE
Handle backends as a mutually exclusive group of features

### ISSUE THREAD

**Issue by hcpl** [gyscos/Cursive#176]
Since `cargo` does not support mutually exclusive groups of features (yet?), my suggestion is to add either of two solutions to `src/lib.rs`.

Common downsides of both approaches are:
- `compile_error!` requires Rust >= 1.20.0.
  * I couldn't find mentions of minimum supported Rust version, so do we care about this? If we do, either semver-bump after this change, or gate this check under `"rust_1_20"` feature, and then the next semver-incompatible version may remove that feature.
- Technically break code that uses `cursive` with 0 or >= 2 backend features.
  * Same concerns as above, but in this case, `"unstable"` might be a more appropriate name.
- Are quite verbose and have code duplication which necessitates double-checking when adding/removing backends.
- Quadratic blowup of lines of code when adding backends.

## Pairs negation-based:

```rust
#[cfg(any(
    all(not(feature = "blt-backend"),
        not(feature = "ncurses-backend"),
        not(feature = "pancurses-backend"),
        not(feature = "termion-backend")),

    all(feature = "blt-backend", feature = "ncurses-backend"),
    all(feature = "blt-backend", feature = "pancurses-backend"),
    all(feature = "blt-backend", feature = "termion-backend"),

    all(feature = "ncurses-backend", feature = "pancurses-backend"),
    all(feature = "ncurses-backend", feature = "termion-backend"),

    all(feature = "pancurses-backend", feature = "termion-backend"),
))]
compile_error!("Exactly one backend must be used with this crate. \
    Please specify either of:
        `features = [\"blt-backend\"]`
        `features = [\"ncurses-backend\"]`
        `features = [\"pancurses-backend\"]`
        `features = [\"termion-backend\"]`");
```

### Pros:

- Shorter.

### Cons

- More difficult to understand the predicate at first glance.

## Valid combinations-based:

```rust
#[cfg(not(any(
    all(feature = "blt-backend",
        not(feature = "ncurses-backend"),
        not(feature = "pancurses-backend"),
        not(feature = "termion-backend")),

    all(not(feature = "blt-backend"),
        feature = "ncurses-backend",
        not(feature = "pancurses-backend"),
        not(feature = "termion-backend")),

    all(not(feature = "blt-backend"),
        not(feature = "ncurses-backend"),
        feature = "pancurses-backend",
        not(feature = "termion-backend")),

    all(not(feature = "blt-backend"),
        not(feature = "ncurses-backend"),
        not(feature = "pancurses-backend"),
        feature = "termion-backend"),
)))]
compile_error!("Exactly one backend must be used with this crate. \
    Please specify either of:
        `features = [\"blt-backend\"]`
        `features = [\"ncurses-backend\"]`
        `features = [\"pancurses-backend\"]`
        `features = [\"termion-backend\"]`");
```

### Pros

- Straightforward to reason about.

### Cons

- Despite both solutions being `O((lines of code)^2)` this one grows with a bigger constant.

**Comment by gyscos** [comment]
Hi!

I think right now a single backend is already a compilation requirement, because we `use` all backends' `Concrete` type in the `backend` module.
As a result, zero backends means the `backend::Concrete` type is missing (compilation error), and 2+ backends mean a name conflict (compilation error).

What we do miss currently is a nice error message indicating why compilation fails, but I'm not sure it warrants this quadratic solution.  Ideally, we would have non-binary features (a `backend` features with multiple possible values), but mutually-exclusive could work as well.

**Comment by gyscos** [comment]
Since 126530b9a9e10bbfc9cb425299bcc9219873d926, backend features are now mutually compatible. Instead of using the only compiled-in backend, the user can now select the backend he wants to use in `Cursive::new`. `Cursive::{termion,ncurses,pancurses,blt}` have been added as shortcuts (if the corresponding feature is enabled).
`Cursive::default()` has been updated to use the first backend available from the list:
* termion
* pancurses
* bear-lib-terminal
* ncurses
The default features are not changed: it is still `ncurses-backend`. This means `Cursive::default()` should still use a ncurses backend by default.

**Comment by hcpl** [comment]
That's a cool new feature, congrats!
And that means this issue has lost its value so I'll close it.
