### ISSUE TITLE
"menubar" example does not work

### ISSUE THREAD

**Issue by avttrue** [gyscos/Cursive#193]
no method named `add_delimiter` found for type `&mut cursive::views::Menubar` in the current scope
  --> src/main.rs:69:10
   |
69 |         .add_delimiter()
   |

**Comment by gyscos** [comment]
Hi!
Indeed, this example was updated on git (when the `add_delimiter` method was added), and no version has been uploaded to crates.io yet.

In the meantime, you can:
* Use the git version of cursive instead of the one published on crates.io (0.7.5)
* Use the previous menubar example: https://github.com/gyscos/Cursive/blob/f90621811cf1bbd9044d853b6718251e0f214353/examples/menubar.rs

**Comment by avttrue** [comment]
Thank
