### ISSUE TITLE
F20 Key.

### ISSUE THREAD

**Issue by IGBC** [gyscos/Cursive#196]
https://docs.rs/cursive/0.1.0/cursive/event/enum.Key.html
Here you list non character keys that are supported. As windows is rather useless I imagine most use for this crate is on *nix systems. Not all Unix systems use IBM keyboards and it is relatively standardised how terminals behave for F Keys up to 20.

> The VT220 provides 8 additional function keys. With a Sun/PC keyboard, access these keys by Control/F1 for F13, etc.
>  ![image](https://user-images.githubusercontent.com/8123843/35465429-372cc71e-02fc-11e8-8f22-de930f85fb35.png)
(From: https://www.xfree86.org/4.8.0/ctlseqs.html)

Can we have F20 key support? (PLZ?)

**Comment by gyscos** [comment]
Hi!

A big part of the problem has to do with the way ncurses parses these sequence codes. When detecting F*n*, it sends the code 264 + *n*. On my machine, when detecting Shift + F*n*, it sends 275 + n. So Shift+F1 on my machine would coincide with F13 on yours, and so on. I'm not even sure what code Shift+F1 would send on in your case (does it send the same code as F13, or a hypothetical F21? You can run the `key_codes` example and ).

In the end I don't think we can easily distinguish between F13 and Shift-F1. And it's not easy to unify `Event::Shift(Key::F1)` with `Event::Key(Key::F13)` so that pattern matching on an event works in both case.

So I'm sure what the best solution is.

**Comment by IGBC** [comment]
From my reading into the docs of Xterm, F13 and ShiftF1*are* actually the same key. Notably, that the documentation states to send F13 on an IBM keyboard you should press control F1. This didn't work on my (IBM based) system and may have been moved to shift.

Either way with control codes for up to 24 F/ShiftF controls I think we're covered.

**Comment by IGBC** [comment]
I also only raised this as I am building a terminal emulator in cursive for embedding into applications (just don't ask) and am trying to stick as close to the Xterm spec. All these things are really badly defined at this point and checking for F20 keys is probably only a problem someone is gonna have running a random sun application inside that terminal emulator. Pretty esoteric

**Comment by gyscos** [comment]
So these key codes are currently parsed, only F13 is not returned as F13 but as Shift+F1 (and I suppose F20 is returned as Shift+F8). So right now, instead of checking if `event == Key(F20)`, you need to check if it is `Shift(F8)`. I understand it is not ideal when writing mappings for these keys.

Let's say F13 and Shift+F1 should be represented with the same enum in Cursive. We can't have `Event::Shift(Key::F1) == Event::Key(Key::F13)`, so we would have to either:
* Sacrifice one of these two and provide a convenience method instead:
    * Only have `Event::Shift(Key::F1)`, and have a method `Event::from_f(13) -> Event::Shift(Key::F1)` for easy conversion.
    * Only have `Event::Key(Key::F13)` and have a method `Event::from_shift_f(1) -> Event::Key(Key::F13)`.
* Not advantage any over the other: have yet another neutral enum, and have both above method to create it.

Note that without `const fn`, we won't be able to use these methods in a pattern match.

**Comment by IGBC** [comment]
Closing, I'm satisfied this is an upstream (ncurses, possibly even VT100) problem.

**Comment by gyscos** [comment]
Note that F20 should still be reliably detected, the "only" problem is when writing down the trigger for it, and when checking received event: in both cases, we currently have to work with `Shift(F8)` which may look confusing - and this is what could be made nicer with some sort of alias.
