### ISSUE TITLE
set_fps is not implemented for blt-backend

### ISSUE THREAD

**Issue by zpgaal** [gyscos/Cursive#239]
blt-backend has no set_fps support and cannot be used for progress update.

I've checked the bear lib and it has no support for event polling with timeout. It could be emulated using two extra threads:
 * One for the user event that blocks in terminal::wait_event call
 * And a timer that sleeps for 1/fps
Each threads feeds some shared (mpsc) channel for the UI and the poll event is a recv for that channel.

(There might be better solution, it just a kind of "brute force" version. And of course thread creation can be skipped when there is no fps settings)

# Environment
* Operating system: windows
* Backend used: blt

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Ah yes, I forgot BearLibTerminal was also blocking for input. As you said, the channel+extra thread solution is problably the way to go.

Note that rather than having a dedicated thread to send a timeout signal, we might be able to use `mpsc::Receiver::recv_timeout`. This'll need further investigation.

**Comment by gyscos** [comment]
The input system was refactored. We now simulate a ~30 constant FPS on BLT.
