### ISSUE TITLE
Additional objects in event handlers?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#241]
Hi,

I am writing a more complex app using Curisve, and I see a need for more than just &mut Cursive in event callbacks. Right now I do some Rc<RefCell<>> magic to put this additional object into a closure that will be eventually called on events, but this feels just bad. Not sure what is the Rust way to do it, but thinking C++ I need something like a delegate.

What are your thoughts?

NJ

**Comment by gyscos** [comment]
Hi!

Let's start with a quick summary of what happens when an event is received by the view:

First, the view can define how to react to the event in its `View::on_event(&mut self, event: Event)`. Here, it doesn't have a referecence to `&mut Cursive`, but it has mutable access to itself and to all its content. A view could be 
```rust
struct MyView<T> { 
    state: T, 
    mutable_callback: Box<FnMut(&mut T)> 
}
```
And its `on_event` could be:

```rust
fn on_event(&mut self, event: Event) -> EventResult {
    self.mutable_callback(&mut self.state);
    EventResult::Consumed(None)
}
```

In this case, you can give the callback mutable access to anything in the `MyView`.

Second, the view returns a `EventResult`. This result indicates if we ignored the event `EventResult::Ignored`, or if we consumed it; in which case the view can include a callback that will be run with a `&mut Cursive`; you can do that with `EventResult::with_cb`. At this point, you can bundle *in the closure* a `Rc` to your data; this is what `SelectView` does for instance. It stores something like 
```rust
pub struct SelectView<T> {
    focus: usize,
    items: Vec<Rc<T>>,
    callback: Rc<Fn(&mut Cursive, &T)>,
}
```

And its on_event can be simplified to:

```rust
fn on_event(&mut self, event: Event) -> EventResult {
    let selected_item = Rc::clone(&self.items[self.focus]);
    let callback = Rc::clone(&self.cb);
    EventResult::with_cb(move |s| callback(s, &selected_item))
}
```

These are the two main ways to give callbacks access to content. You can add a `RefCell` if the callback needs mutable access to the content, but it's the same idea.

C++'s delegates are really just closures in Rust. `Rc` and `RefCell` are really not a bad thing, their performance impact is virtually nothing, and they're the main way to achieve safely what the soup of pointers gets you in C/C++.

**Comment by njskalski** [comment]
Thank you for the detailed explanation!
