### ISSUE TITLE
I have a bug

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#252]
Hi, I found a bug, which I cannot share today (still waiting for clearance on code publication), but I can desribe it.

As long as I put 3 views in LinearLayout (Horizontal), I get them all drawn one after another, everything works fine.

But If I put it to Horizontal(View1, Vertical(View2, View3)), the View3 (edit_view) gets palette colors mixed. Basically the background and font color set to black, no matter which color theme/palette I use.

If you have an idea what this might be, let me know. If not, I will try to do a minimal repro and push it during weekend.

**Comment by njskalski** [comment]
Actually changing the order on LinearLayouts retains the error.

**Comment by njskalski** [comment]
https://github.com/njskalski/bug2 it's BoxView issue.

**Comment by gyscos** [comment]
This is what I see when running the `bug2` project:
![screenshot from 2018-05-23 15-37-31](https://user-images.githubusercontent.com/564903/40454897-6c9b13de-5e9f-11e8-8bce-75ba8421600e.png)

The left half is the tree view. The right half is the `SelectView` on top, and an `EditView` on the bottom.
The `EditView` is single-line only (if you want multi-line, you'll need a `TextArea`).

There _is_ a bug when the window is too small, where the `EditView` is drawn over the shadow:
![screenshot from 2018-05-23 15-41-21](https://user-images.githubusercontent.com/564903/40454987-c4a82f30-5e9f-11e8-84d9-e1179b6190ba.png)

It should either be drawn within the window frame, or not be drawn at all. But that's a degenerate case where the layout cannot fit in the given space.

What is the problem you're describing?

**Comment by njskalski** [comment]
Well it looks like the second example. The letters in edit view seem to be
hidden. That’s so weird. I thought I have disabled the shadows. Will look
more into it tomorrow. It’s 1am in Zurich.

**Comment by gyscos** [comment]
So in the second example, there is not enough space to display the content (since you specified no-compromise fixed sizes in `BoxView`). This means the `LinearLayout` cannot find a working layout, so it tries a "best effort" solution. In this case it tries to print the `EditView` _outside_ of the window frame, into shadow territory. This should not be allowed, and is a bug. The result is that instead of seeing the layer shadow, we see the `EditView` itself. It seems also that if you write content, the content of the editview is not drawn (this is the normal behavior) and we see the shadow.

So apparently when drawing the background of the `EditView`, somehow we bypass the usual rules and we're able to draw outside of the frame. This is a bug with the bound checks when drawing lines (as opposed to when drawing text). This is probably fixed on master, but I'll check to be sure.

**Comment by njskalski** [comment]
Yeah, I made boxes smaller and it fixed the bug in my app. Thank you!
