### ISSUE TITLE
Feature request: Add new methods to `View` to control visibility.

### ISSUE THREAD

**Issue by sandeep-datta** [gyscos/Cursive#258]
Please consider adding some methods to the `View` trait which let the user hide and unhide views / widgets. This can be used to selectively provide the user of the terminal App with more information as the they interact with the program. This conceptually simple change will make the creation of dynamically changing user interfaces much easier.

I would suggest adding methods like `is_visible() -> bool`, `set_visibility(is_visible: bool)` to handle this. The implementors will need to take the visibility status of child views into consideration during layout computations and drawing operations.

Also consider adding  `hide()` and `unhide()` with default implementations to `View` based on the above mentioned methods.

Edit: while we are at it we should also consider adding support for enabling and disabling controls. Something like `is_enabled() -> bool` and `enable(is_enabled: bool)`. The user should not be able to interact with disabled controls even though they may be visible. Disabled controls should have a "grayed" out appearance which gives a visual indication of their disabled state. 

Also consider adding  `enable()` and `disable()` to `View` with default implementations based on the above mentioned methods. Note:

**Comment by gyscos** [comment]
Hi, and thanks for the input!

This sounds like it could be done in a wrapper view. Instead of adding these methods to the `View` trait, and adding a boolean flag to every view, we could define a `VisibilityWrapper` or something that would embed this logic.

By default it would just forward everything to the wrapped view, but when hidden, it would pretend that it doesn't exist (take zero space, no draw anything, not take any input, ...).

Regarding enabled/disabled state, right now it's handled per-view: for instance, both EditView and Checkbox define their own state and methods.
This is mostly fine for individual views, but I see now that it becomes tricky when we want to disable a full subtree from the layout (for instance disable every fields in a panel).

To get there, I think it makes sense to put the "enabled" state in the printer, just like "focused" currently is. This is the main way to have parameters apply to a whole subtree.
Once this state is standard in the printer, we could have a `ToggleableWrapper` (name still TBD) with an internal "enabled" state. This wrapper would apply its state to the printer before giving it to the wrapped view. It would also discard events if disabled.

**Comment by sandeep-datta** [comment]
> we could define something like a VisibilityWrapper that would embed this logic

+1 I like this! Though we should probably call it something like HideableView taking a cue from how iterator and their wrappers are named (e.g. DoubleEndedIterator).

> To get there, I think it makes sense to put the "enabled" state in the printer, just like "focused" currently is. This is the main way to have parameters apply to a whole subtree.

I don't know enough about the internals to comment on this but I will go through the code and get back to you.

**Comment by gyscos** [comment]
d52299a6e1fdc65d76105810653ed5340c3ad16f adds `HideableView`.
For the enabled thing, I think I'll wait until after the `scroll` branch has been merged, as it might conflict with `Printer` otherwise.

**Comment by TerminalWitchcraft** [comment]
@gyscos will the `HideableView` feature land in the next release of Cursive?

**Comment by TerminalWitchcraft** [comment]
Thanks! didn't notice that. I had checked the changelog.md file but couldn't find. Hence the question. Anyways, thanks for pointing out.
