### ISSUE TITLE
Feature request: Add a generic `model` parameter to `Cursive`.

### ISSUE THREAD

**Issue by sandeep-datta** [gyscos/Cursive#262]
The callbacks as they are implemented now (using static lifetimes) limit what can be captured in closures. 

Adding a generic data member called `model` to the `Cursive` struct may be a good way of avoiding the aforementioned limitation. This model can then be accessed from callbacks using a method called `model()` to get a shared reference to the model and a method called `mut_model()` to get a mutable reference to the model. Note: all callbacks are passed a reference to the `Cursive` struct by default.

Thoughts?

**Comment by gyscos** [comment]
Hi!
It's a very interesting idea!

One solution would be to make have `Cursive<T>` with a `model: T`, but there's a problem with this: it means _every_ place where we use a `Cursive`, we have to take this generic parameter into account.
In practice, this means most views would need to be `T`-generic themselves, even views that don't access the model. This ends up being quite messy, and a sensible loss in convenience.

Instead, we could store this information in runtime instead of compile-time. This means storing something like `Box<Any>`, and offering methods like `Cursive::model<T>(&self) -> Option<&T>` - this would let users get the type they stored, without adding a type parameter everywhere.

**Comment by sandeep-datta** [comment]
Awesome idea @gyscos. I am still learning Rust and it seems a lot of it from you :) thanks!

**Comment by gyscos** [comment]
The master branch now brings `Cursive::set_user_data`, `Cursive::user_data` and `Cursive::with_user_data` to cover this use-case. Tell me if it works for you! :)

**Comment by sandeep-datta** [comment]
Looks great! Thanks! :)
