### ISSUE TITLE
Suggestion: Make allow global event handlers to be FnMut and not just Fn

### ISSUE THREAD

**Issue by delbonis** [gyscos/Cursive#274]
If there's some data in the closure for a global event handler that needs to be mutated it's a real pain to make that happen when you're using an `Fn` since `Fn`s aren't allowed to mutate their closure.

It generally involves doing a `mem::transmute::<&mut _, *mut _>` and back.

**Comment by gyscos** [comment]
I would think it'd involve a `Rc`+`ReffCell` rather than a transmute, which could lead to UB.

As for the callbacks, they are `Fn` because it's possible, from the callback, to access itself (since it has access to `&mut Cursive`. This is only safe if the callback is not borrowed mutably, as it would if it was `FnMut`.

That being said, it's pretty easy to wrap a FnMut on a RefCell and stick that in a Fn, you just lose reentrance. I updated add_glibal_callback to do this for you.

**Comment by gyscos** [comment]
Released as part of 0.9.0.
