### ISSUE TITLE
[Help] Implement chaining(composition) of keystrokes?

### ISSUE THREAD

**Issue by TerminalWitchcraft** [gyscos/Cursive#285]
Is there a way to chain input events into functions such as `on_pre_event`, `on_pre_event_inner` etc? or any workaround? I am trying to implement vim-like keybindings into my terminal application and would like to support commands such as `gg`, `2d`, `12G`, etc. AFAIK, `Event` type could be a character or chained with some modifier such as `CtrlChar` and so on. I am looking to chain multiple alphanumeric keys, without any limitation on length. For example, `2d` will delete two items down, `20G` will select the 20th item in SelectView, etc.

Any help would be greatly appreciated,

Thanks,
Hitesh Paul

**Comment by gyscos** [comment]
Hi!

This sounds like a great use-case.

To be compatible with most views, the easiest solution would be to convert these "chained" events into regular events.

`OnEventView` is not ideal for that as you'd have to set individual callbacks for each event (each letter/number).

Instead, you could write your own `WrapperView` and override `wrap_on_event`. For testing, you can also just use a `Canvas`:

Using the new `EventResult::and`:

```rust
let main_view = make_main_view();
let mut previous_keys = Vec::new();
let canvas = Canvas::wrap(main_view)
    .with_on_event(move |child, event: Event| {
        if should_intercept(&event, &previous_keys) {
            previous_keys.push(event);
            // Combine the events into something bigger, for example 20x down
            let mut result = EventResult::Ignored;
            for _ in 1..20 {
                result = result.and(child.on_event(Event::Key(Key::Down)));
            }
            result
        } else {
            child.on_event(event)
        }
    });
```

Or, using the new `Cursive::on_event`:

```rust
// ...
        if chain_event(&event, &previous_keys) {
            previous_keys.push(event);
            // Combine the events into something bigger, for example 20x down
            EventResult::with_cb(|siv| {
                for _ in 1..20 {
                    siv.on_event(Event::Key(Key::Down));
                }
            })
        } else {
            child.on_event(event)
        }
// ...
```
The second example will have the simulated input go all the way the view tree, including this wrapper, so it can only simulate events it itself does not intercept. It will also let cursive react to any callback caused by the simulated events: if scrolling down triggers a popup to show, the first solution will still scroll down 20 times, then show the popup (possibly multiple times); while the second example will show the popup and this popup may consumes the remaining "down" events.

**Comment by TerminalWitchcraft** [comment]
Hi, Sorry for the late reply, I was writing some error handling for the app. 

Your first solution works like a charm, although I haven't tested the corner cases such as popup windows, etc. I will test some corner cases and will give the second solution a try. If I encounter any strange behaviour, I will report it here. For now, I am closing this issue.

Thanks,

**Comment by gyscos** [comment]
Glad to hear it solved your issue!

As a note, `Canvas` can be convenient to quickly try something like that, but if you never change the callbacks, it can be a bit more efficient to define your own type and implement `View` (or `ViewWrapper`) on it. This way, you will get static dispatch (`Canvas` is doing dynamic dispatch for all methods).

**Comment by TerminalWitchcraft** [comment]
Thanks for the suggestion! I tried `ViewWrapper`, but it seems according to my use-case, creating a custom struct and implementing `View` trait would be beneficial(Because I need to pass more arguments to callback functions, such as `set_on_select` for `SelectView`, where I am currently limited to `&mut Cursive` and `&T`.

I am stuck with the following thing(It's not related to this issue, but opening a new one for the same isn't worth either, so I'm mentioning here). My current project structure looks like the following:

```rust
struct MyApp {
   siv: Cursive,
   field1: fieldType1,
   field2: fieldType2,
   ...
}

impl MyApp {
   pub fn new() -> Self {
   // some code
   }

   pub fn add_tab(&mut self, param1, param2) -> Self {
   let mut sel_view = SelectView::default();
   // Add items to the view
    
   // Add key-bindings
   let event_view = OnEventView::new(sel_view)
        .on_pre_event_inner('k', |s| {})
        .on_pre_event('h', |siv: &mut Cursive| {
        // How can I use a field of the current struct?
        // For example, I want to use self.field1 to compute
        // in order to process this callback
        let some_value = some_function(&self.field1);
        });
   self.siv.add_layer(event_view);
   }
```
How can I use a field of my `struct` inside callbacks, like `on_pre_event`, `add_global_callback`, etc?

This is my first major project in Rust and I have spent a fair amount of time figuring out how this can be implemented(I am coming from an OO programming background), but couldn't find a way. 

I also tried to figure out, how does `OnEventView` gets access to `Cursive` object? I tried implementing something similar but no luck! If you could help me with some pointers or ideas, I would greatly appreciate it!

Thanks,
Hitesh Paul

[Link](https://github.com/TerminalWitchcraft/marcos/blob/6d025756ef92eb03723b58050ce3b0b288f8ab26/src/core/app.rs#L49) to source code if needed.

**Comment by gyscos** [comment]
Your code in, say, `on_pre_event`, needs to access a variable. There are multiple options for this to happen, from most specific to most general:
* The code can be "given" access to a variable when it executes, as part of the closure arguments. In most callbacks, this happens for `&mut Cursive`, but since the interface of the closure is fixed, you cannot add much more than that. Note the in the case of `on_pre_event_inner`, the value given is the wrapped view, `SelectView` in this case. So if the field you need is there, you can use that.
* The code can "own" a variable: if you declare your closure as "move" (`move || {}`), it will try to own exclusively the variables it captures. This is useful if the closure is the only place where you access this variable, for example an accumulator.
* The code can "share" a variable: using [`Rc`](https://doc.rust-lang.org/std/rc/struct.Rc.html) (and `RefCell` if you need mutability), you can keep multiple "references" to the same data. For this, you need to keep a `field1: Rc<RefCell<FieldType1>>`. You can give a `clone` of the `Rc` to the closure in your callback, and it will reference the same `FieldType1`.

**Comment by TerminalWitchcraft** [comment]
Thanks for the pointers and detailed explanation! It solved my problem. I resorted to using `Rc<RefCell>` type. It seems I have to polish some untouched corners of Rust programming :smiley: 

Thanks again,
Hitesh Paul
