### ISSUE TITLE
FnMut for Buttons of a Dialog or other methods?

### ISSUE THREAD

**Issue by ibutra** [gyscos/Cursive#286]
Asking for help.

# Problem description
Hi,
I am quite new to Rust and Cursive so excuse me if the solution is obvious.
I am currently trying to have a Cursive Dialog to edit the fields of a struct. It works as far as me getting the values out of the struct and showing them with Cursive. Where I am struggeling is mutating the struct when the dialog is closed.
My specifig problem is, that the buttons of a dialog require a Fn and don't allow for an FnMut.
This prevents me from changing the struct captured in a closure.
I found the issue #108 which seems to be related but as far as I can tell something similar has not been implemented for Buttons.
I realize I can just copy the solution of it, but I figured this is probably a common problem and am wondering if there is a "better" or more idiomatic way?

# Environment

* Operating system: macOS
* Backend used: ncurses (the default one)
* Current locale:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```
* Cursive version 0.9.0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, it is the same problem as #108, and the same workaround applies: we could "fake" a `FnMut` from a `Fn` by wrapping the `Fn` in a `RefCell` and mutating it when we can.
This means that, if the callback injects an event that would trigger the same callback, it will not run a second time. This is not a super common thing, so it's probably not a problem for you, but it's something you may have to keep in mind because it can be surprising if you don't expect it.

I wish this solution of "wrap a `Fn` in a `RefCell` and publish it as a `FnMut`" would be easier to automate, but I can add a matching function for now.

Note that an equivalent solution would be to wrap the struct you want to modify in a `RefCell`. This is often needed anyway if struct itself needs to be accessed from another location.

**Comment by gyscos** [comment]
Just pushed something that adds 3 macros: `immut1!`, `immut2!` and `immut3!`. Each wrap a closure/function with the corresponding number of arguments.
So in your case you'd use `immut1(|s: &mut Cursive| { ... })`.
This is still a bit experimental.

**Comment by ibutra** [comment]
Hi, sorry for the silence, I was on holiday.

Thank you for the answeres and added macros. 
Isn't the limitation to not fire callbacks recusively quite common for gui frameworks?

**Comment by gyscos** [comment]
It might be? I admit I never touched this kind of limits.
But I can imagine cases where you'd want recursive call, so I don't think preventing it entirely is ideal.
