### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by matthiasbeyer** [gyscos/Cursive#29]
Would be nice to have something like a progress bar which can be updated from a thread or something...

**Comment by gyscos** [comment]
Yup, planned.
This kind of new view can actually be done outside of this library (just implement the View trait), so they're less of a priority, while internal things (like menubar or better layout engine) have to be done here.

**Comment by gyscos** [comment]
An initial implementation has been added (with `examples/progress.rs` using it):

![progress](https://cloud.githubusercontent.com/assets/564903/17125015/c4e1ee90-52a4-11e6-943d-8ddd138249c8.gif)

Still TODO:
* Show progress in the center of the bar
* Nicer API (directly give a closure to the progress bar, tick-based progress...)

**Comment by matthiasbeyer** [comment]
I just had a look at the progress bar implementation. Maybe it would make sense to be able to get the `Arc` from it as a `&Arc`, so I can pass it around in my program to update it. Not sure whether this would be good API design, though.

**Comment by gyscos** [comment]
The current implementation was focused on starting the task as soon as the progressbar is created.

Now I see cases where you'd want the progress bar to always be present, and start it from somewhere else in the UI. I'll add ways to access (or set) the `Arc` outside of the constructor.

Though dealing directly with the `Arc` is still the manual way for people who needs more control, ideally the more common way to update it will be though a single closure given at creation, or though a `start` method.

**Comment by matthiasbeyer** [comment]
I have another idea... maybe a bit far-fetched, but as rust gives us power to do parallel stuff without much effort, it might be a good idea to offer multi-progress-bars, so one can have 1..n progress bars in one window.

I will try to hack this myself now and ping you if I do not succeed! :-)

**Comment by gyscos** [comment]
Having multiple progress bars, for instance in a LinearLayout, should work well.
However, the clunky way to give the callback is even worse to coordinate multiple bars...

**Comment by matthiasbeyer** [comment]
Okay, I guess this is too hard for me right now, I'm sorry.

**Comment by gyscos** [comment]
Callback management has been moved to the Cursive root (using a callback channel), and the progress bar now can take a closure to execute in a thread, along with a tick-based progress communication (`examples/progress.rs` has been updated to use it).
It works well when a separate thread can be called for the task. But when this is not desired, maybe because multiple progress bars are visible but only one thread shall be used for all the tasks (or for other situations where a more manual approach is preferred), having to go the full DIY way is quite inconvenient - the `AtomicUsize` especially exposes a lot of implementation details and has a complex API when all we want is to increment a counter.

A solution would be to wrap the `Arc<AtomicUsize>` into a custom type, and implement `tick(&mut self, usize)` on it, and maybe `get(&self) -> usize`.

**Comment by gyscos** [comment]
Ok, the example has been boosted with multiple loading bars to show the two different progress reporting methods: directly through a closure, or by updating the counter externally.
