### ISSUE TITLE
Scrollbars not rendering properly with ncurses

### ISSUE THREAD

**Issue by zk-ncc** [gyscos/Cursive#303]
Bug report:

# Problem description

Vertical and horizontal scrollbars are looking broken on v0.10+ using ncurses. It seems to generating invalid escape sequences. I guess it's possible this has nothing to do with scrollbars specifically, but that is where I encountered it. Here is a screenshot of a minimal example:

<img width="758" alt="cursive" src="https://user-images.githubusercontent.com/23707611/50362986-871df500-052f-11e9-8d9c-e490f942abde.PNG">

And the code for that example:

```rust
fn main() {
    use cursive::views::{ScrollView, TextView};
    use cursive::Cursive;

    let mut siv = Cursive::default();
    siv.add_global_callback('q', |s| s.quit());

    let mut huge_text = String::new();
    for h in 0..50 {
        huge_text.push_str("abcdef ");
    }
    for v in 0..150 {
        huge_text.push_str("\na");
    }
    siv.add_layer(ScrollView::new(TextView::new(huge_text).no_wrap()).scroll_x(true));
    siv.run();
}
```

I `git bisect`ed the problem to this commit:

```
commit 79e23bb70ed7fb756199770d10e3a3abe730d1b5
Author: Alexandre Bury <alexandre.bury@gmail.com>
Date:   Fri Nov 30 16:55:47 2018 -0800

    Update dependencies
```

While bisecting, the dependency versions didn't seem to change (only cursive and the app crate itself had any compiling/updating output from cargo), so I'm not sure the problem is in a dependency change.

# Environment

* OS: Arch Linux
* Terminal: xfce4-terminal
* $TERM: xterm-256color
* Backend: ncurses
* ncurses version: 6.1
* Locale: en_US.UTF-8
* Cursive version: v0.10, git (see hash above)

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Unfortunately I'm not seeing the problem locally. If it seems to involve dependency updates, did you try running `cargo update`? The `ncurses` crate is often not really following semver, which may causes some surprises now and then (though usually it would cause old versions of cursive to fail compilation rather than this).

It's also possible that your terminal does not like utf8 characters (maybe the locale needs rebuilding?).
Does window borders work? (You can try the `dialog` example, or wrap your view in a `Dialog`).

**Comment by zk-ncc** [comment]
Good news, I can't reproduce this anymore either. It went away after doing a system update today. So that was an unfortunate coincidence. I'll close this now. Thanks for taking a look!
