### ISSUE TITLE
Single app on multiple ttys?

### ISSUE THREAD

**Issue by njskalski** [gyscos/Cursive#312]
I am writing my editor, and I think that instead of implementing my own multi-window system, it would be best to allow people to use tmux. So - from what I understand - it would just require a single app to use several tty input-outputs, right? Is it possible to do it with cursive? How much change would be needed to achieve that?

**Comment by gyscos** [comment]
I think it would be much easier to have one process per tty, and use some inter-process communication to coordinate them (Unix socket, dbus, named pipe, ...).

**Comment by njskalski** [comment]
Like that I run multiple instances of my program and communicate between them with IPC? Well that's a plan B, but given the indexing effort, and LSP integration I would have to create some "primary" instance and then serialize and deserialize everything. I was thinking that maybe working with multiple ttys would save me the hassle.

**Comment by gyscos** [comment]
The alternative is to spawn a new thread, create a new backend that could attach to the desired tty rather than the default one (probably based on termion, as ncurses is annoyingly thread-unsafe), and have one cursive loop per thread/tty.

You would also have to somehow communicate to the app which tty you want to start using.

So each tty would be handled by its own thread with its own cursive instance - it's not that different from individual processes. You could use https://github.com/servo/ipc-channel to make communication easy, or even just share memory: https://github.com/elast0ny/shared_memory-rs.

**Comment by gyscos** [comment]
Disclaimer: I have _no idea_ what happens when you attach a single process to multiple ttys, especially regarding signal handling. Most backends currently listen to `SIGWINCH` to detect terminal size changes, so this might need some attention if you want multiple backends to run in the same process.

**Comment by njskalski** [comment]
I forgot about signals. Now I agree with you, I'll go multiprocess. Thanks.
