### ISSUE TITLE
[Question] How to find out why I can't find a view

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#317]
I am wrestling through upgrading an application from an old Cursive to the current one. Mostly this was not too much effort, but at this point I am stumped. The code registers a callback with `SelectView.set_on_select` which uses `s.find_id(VIEW_ID_DETAILS)` which used to present the details for every account in the selectview. However, in the new Cursive it finds `None` in stead of the view id specified. 

I was looking for a way to find out which ID's the current cursive has, but I can find none in the docs. 

Is there a way to find out why a TextView in the cursive with ID cannot be found?
I.e. I am trying to find a way how to approach this. 

I you need it, I can give you the code, but it's a lot. The module is in github: simmons/tupm under `src/bin/tupm/ui.rs` at line 694 which does an `account_list.set_on_select` calling the same method of SelectView (the type of account_list). The branch is fix_incompatibilities. My repo has a fork (gbonnema).

**Comment by gyscos** [comment]
Hi!

Regarding the debugging itself, I usually start gdb and manually inspect the call (often I use rr and use back-steps from a panic).

I understand it's not exactly ideal, and I'd love to have a way to easily print the full view tree for debugging; I'm still thinking about a nice way to integrate this in the View API.

Otherwise, the usual causes for not finding a view you expect are:
* Typo in the name
* The exact type is wrong (maybe it's now a BoxView, not a TextView anymore)
* The view (or view tree) was already removed
* Part of the view tree is currently being borrowed. This doesn't happen often, as the API tries to discourage keeping a borrow open, but it can happen if you're borrowing a direct parent already. In this case, you can usually call call_on or find_id on the parent view itself (through the `Finder` trait).

**Comment by gyscos** [comment]
Looked at your branch, and I'm pretty sure the cause is that you now have a `IdView<ScrollView<TextView>>`, so `find_id` should look for a `ScrollView<TextView>`. Alternatively, you could do this:

```rust
 let account_detail = TextView::new("").with_id(VIEW_ID_DETAIL).scrollable();
```

This would get you a `ScrollView<IdView<TextView>>`. The downside is that you cannot "find" the scroll view itself, but you probably don't need it anyway.

**Comment by gbonnema** [comment]
I just verified: you are completely right!  Thank you very much! 

I was looking into whether BoxView was the cause, which turned out not to be the problem.

As a byproduct of your research, I understand the ID a little better. Again: thank you!

**Comment by gyscos** [comment]
Glad your problem is solved! :)
