### ISSUE TITLE
[Question] using variable to catch 2 Identifiables

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#320]
Looking at some duplicate code I would like to eliminate, I wander into new territory to me. The code looks like this:

```
           if !field.multiline {
                v_layout.add_child(
                    LinearLayout::horizontal()
                        .child(TextView::new(labelify(field.name)))
                        .child(BoxView::new(
                            SizeConstraint::AtLeast(30),
                            SizeConstraint::AtMost(1),
                            edit_view.with_id(id),
                        )),
                );
            } else {
                v_layout.add_child(
                    LinearLayout::vertical()
                        .child(TextView::new(labelify(field.name)))
                        .child(BoxView::new(
                            SizeConstraint::AtLeast(30),
                            SizeConstraint::Fixed(10),
                            TextArea::new().with_id(id),
                        )),
                );
            }
```

What I wanted to do was put the size constraint and the view into a variable. The size constraint works fine: 

```
            let _x = {
                if field.multiline {
                    SizeConstraint::Fixed(10)
                } else {
                    SizeConstraint::AtMost(1)
                }
            };
```

The view I cannot seem to allocate to a variable. I found in Cursive that all views are Identifiable, but the compiler will not swallow this:

```
           let _y: Identifiable = {
                if field.multiline {
                    edit_view
                } else {
                    TextArea::new()
                }
            };
```
The reason is that the variable _y does not have a fixed length.

Do you know of a way to eliminate the code duplication?

**Comment by gyscos** [comment]
The problem is that `EditView` and `TextArea` are two different types. It's the same problem as if you wanted to work generically with `i32` or `i64`.

There are two main ways to re-use code in this situation:
* Force the two variables to have the same type, usually via a trait object. Here, you use `ViewBox` for that (very different from `BoxedView`! It's a sad naming conflict :( ):
```rust
let view: ViewBox = if field.multiline {
    ViewBox::boxed(edit_view)
} else {
    ViewBox::boxed(TextArea::new())
};
```
Since `ViewBox` is a `View` itself, it is `Identifiable`.
Note that this requires an allocation (it uses a `Box<dyn View>` internally), so it's not the _most_ efficient solution, but in general it's far from a problem. The thing to remember is that the view being wrapped will now be a `ViewBox`.

* Reverse the code, and use a generic function to process either type of view.

```rust
fn add_view<V: View>(layout: &mut LinearLayout, view: V, width: SizeConstraint, height: SizeConstraint) {
    layout.add_child(BoxView::new(width, height, v.with_id(id)));
}

if field.multiline {
    add_view(&mut layout, edit_view, x, y);
} else {
    add_view(&mut layout, TextArea::new(), x, y);
}
```
or something like that.
In this case, we avoid an allocation and dynamic dispatch, so there's a _little_ performance improvement, and the view being wrapped is now directly either `EditView` or `TextArea`. The main problem is that it forces a code reorganisation to move the duplicated code in a generic function.

**Comment by gbonnema** [comment]
Thanks for the answer. I like the second option and will consider using that: thanks!

Kind regards, Guus.
