### ISSUE TITLE
[Question] Why do returns of get_content differ?

### ISSUE THREAD

**Issue by gbonnema** [gyscos/Cursive#336]
While working on #334 I was using the result from `TextArea::get_content()` and `EditView::get_content()` and found that the TextArea I could use `String::from()` but the EditView I could not (From trait not implemented). I could solve it using a `clone()` because the result of `EditView::get_content()` is a `&str`, but I was wondering why there is a difference.

Looking at the respective headers I saw the following code for TextArea: `pub fn get_content(&self) -> TextContentRef` and for EditView: `pub fn get_content(&self) -> Rc<String>`, which at least partly explains the difference. Still, why the lock for TextArea is needed eludes me. 

Also, the TextContentRef comments that states you can deref() the String, but not store it due to a lock. If I use `String::from(text_area.get_content().deref())` on the TextContentRef it should be a copy and not disturb the lock?

**Comment by gyscos** [comment]
Maybe you mean `TextView` rather than `TextArea`?

Currently:
* `TextArea` still has a very simple storage model (a `String`) and exposes a `&str`
* `EditView` stores a `Rc<String>` internally, and exposes it directly. This makes it easier to refer to the content of the view in callbacks, but beware! The returned `Rc<String>` will not stay in sync with the content of the `EditView` - it just represents the value of the view when you call `get_content`.
* `TextView` stores a `TextContent` internally, which will stay in sync with the view content. It can even be used to update the content of the view "remotely". This was an experiment to detach the view from the model (so you could update the "content" in your application logic without thinking about the view). It's still in progress so may not be very ergonomic yet. 

In addition, a `TextView` can store more than just plain text: it can store _styled_ text. This is why `TextContentRef` does not derefs to `str`, but to `StyledString`. It can potentially be markdown text, or other markups. You can call `source()` to access the string used to create this. If the `TextView` has plain text, it will just be this text. If the content was set from markdown, it will be the base markdown text.

The documentation says that `TextContentRef` locks something and you should not store it. Indeed, what you'll do instead is:

* Get a `TextContentRef` from `TextView::get_content()`
* Call `.source()` on it to retrieve a `&str`
* Create a new `String` (or `TextView` or anything) from this `&str`
* Drop the `TextContentRef` automatically once it gets out of scope

All this can be done with:

```rust
let content = self.call_on_id("text_view", |text_view: &mut TextView| {
    String::new(text_view.get_content().source())
}).unwrap();
```

This way, you don't store the `TextContentRef` itself.

**Comment by gbonnema** [comment]
That is impressive! 

So I could have the `StyledString` or a `String` depending on what I need. Nice. How about `get_content` returning `&str` or `String` and `get_styled_content` returning `StyledString`? Would that bypass having to use the lock? It would be used internally ofc.

**Comment by gyscos** [comment]
The problem is that going from `StyledString` to `&str` is not always _obvious_. If a textview has some markdown text, should the content return the markdown source? Or the text itself without any markup?
Because of this ambiguity, I chose at first to just return the `StyledString` and let the user decide what to do, potentially simply calling `.source()`.

The lock is still present, but hopefully only lasts for a little while, since you'll drop the `TextContentRef` soon enough.

**Comment by gbonnema** [comment]
ok, fair enough.
