### ISSUE TITLE
[Help] Changing the window title.

### ISSUE THREAD

**Issue by T-Hacker** [gyscos/cursive#380]
How can I change the window title?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Changing the title of the terminal is not currently supported (there are some plans for that, but nothing so far).

**Comment by vmedea** [comment]
Hehe yes, forget getting window title changing into ncurses, I did a search and apparently people have been trying since 2004 !… pdcurses does have `PDC_set_title`.

Fairly sure it'd be welcome in termion and crossterm.

I think bearlib is the only backend that can already do it, with `terminal::set((config::Window::empty().title(…));`.

**Comment by gyscos** [comment]
I just found about crossterm's [`terminal::SetTitle`](https://docs.rs/crossterm/latest/crossterm/terminal/struct.SetTitle.html) which might be used for that.

Nothing from termion or ncurses so far.

Note that since it's relatively small, we may have an implementation in cursive itself for these backends, similar to the one from crossterm.

That's what I did in the latest commit. No implementation for windows on pancurses yet, but all of ncurses, termion, crossterm, and bear-lib-terminal should handle it.
