### ISSUE TITLE
Add support for generating label's with a callback in selectview

### ISSUE THREAD

**Issue by alexanderkjall** [gyscos/cursive#414]
First: is this a bug report? A suggestion? Or asking for help?
This is a feature request

# Problem description
In ripasso we have a list of password files, and display some meta information that we fetch from a git repository.

This fetching can be expensive, and if the user have a large amount of passwords then it can get out of hand, it would therefore be nice to be able to only compute this if the password is displayed to the end user.

If it would be able to add items to the selectview together with a callback function that would calculate the label when needed it would reduce the startup time for those users immensely.

If possible code, or pseudo-code to reproduce the problem / present an idea.

# Environment

* Operating system: linux distribution, windows, macOS, ...
* Backend used: ncurses (the default one), pancurses, termion, ...
  * If using ncurses on linux, ncurses version? (run `grep "define NCURSES_VERSION " /usr/include/curses.h`)
* Current locale (run `locale` in a terminal).
* Cursive version (from crates.io, from git, ...)

**Comment by gyscos** [comment]
Thanks for the report!

I'm not sure I completely understand the feature. Do you want to add a large numbers of items to a scrolling list, and only compute the actual text when the user scrolls to this row?
You would have a long list (`ListView`? `LinearLayout`?) of "dummy" rows, and you would only "materialize" these dummy rows into correct values when needed, which is when they scroll in view.

I now realize that we're missing something like a `on_scroll` callback on `ScrollView`, so you could add a hook there and re-compute the rows as desired. It starts to be a bit tricky if you want to start fetching the data _before_ it is actually visible, so that you don't block the main thread, _and_ the user rarely sees the dummy item. That's where a scroll-based hook is more flexible than a hook on the `draw` event.

**Comment by alexanderkjall** [comment]
Your idea of `on_scroll` sounds like what I was aiming for, I'm far from an expert in how to keep the UI responsive and flexible.

We might solve the problem in ripasso in some other way, but I thought it would be useful to be able to not pre-compute the label values.
