### ISSUE TITLE
Various approaches to UI scaling not working

### ISSUE THREAD

**Issue by compenguy** [gyscos/cursive#431]
I don't know if I have a bug (bugs?) or not, so I'm starting with a request for help.

# Problem description

1. I'm trying to adjust how my UI scales with terminal height.  A registered a global callback on the Event::WindowResize event, with my ui_scale() function as the Fn argument, and as far as I can tell it never gets called as I resize the terminal window.
1. Because (I assume) no WindowResize event would be issued on application startup, I hard code an initial call to my ui_scale() function.  Logging shows that the function _is_ being called.
1. In my ui_scale() function, I call_on_name() some hideables and hide or show them based on the reported screen_size() y height. My detection of terminal height works fine, but my calls to hide/show elements has no effect.
1. There are always at least two blank lines displayed, so that if the height is 2, no UI controls are ever rendered.

For reference, here's my ui_scale() function:
```rust
    pub(crate) fn ui_scale(s: &mut Cursive) {
        let height = s.screen_size().y;
        trace!("Window resize. New height: {}", height);
        match height {
            h if h <= 3 => {
                trace!("Hiding spacer");
                s.call_on_name("spacer_hideable", |v: &mut HideableView<DummyView>| {
                    v.hide();
                });
                trace!("Hiding stations");
                s.call_on_name("stations_hideable", |v: &mut HideableView<SelectView<String>>| {
                    v.hide();
                });
            }
            h if h <= 5 => {
                trace!("Hiding spacer");
                s.call_on_name("spacer_hideable", |v: &mut HideableView<DummyView>| {
                    v.hide();
                });
                trace!("Showing stations");
                s.call_on_name("stations_hideable", |v: &mut HideableView<SelectView<String>>| {
                    v.unhide();
                });
            }
            _ => {
                trace!("Showing spacer");
                s.call_on_name("spacer_hideable", |v: &mut HideableView<DummyView>| {
                    v.unhide();
                });
                trace!("Showing stations");
                s.call_on_name("stations_hideable", |v: &mut HideableView<SelectView<String>>| {
                    v.unhide();
                });
            }
        }
    }
```

# Environment

* Operating system: debian buster linux
* Backend used: crossterm
* Current locale: en_US.UTF-8
* Cursive version: [Current git](https://github.com/gyscos/cursive.git#5423a9a0034bc9621a8d98d0aada29d48990e6b3) (I need git for the fix I submitted for SelectView panics)

**Comment by compenguy** [comment]
Regarding item 4 on the above list, I was able to reduce the dead space to 1 by switching to "add_fullscreen_layer()" in place of "add_layer()", but I still have the problem of no UI getting drawn when I shrink the terminal down to one line.

I also forgot to mention that I can't figure out what weights to on LinearLayouts, but I tried messing with those to modify which controls stop getting rendered when shrinking the UI, but it didn't seem to have any effect.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Regarding the weights of `LinearLayout`, it's still a work-in-progress and is not doing anything right now. :(

By default, adding views to the `StackView` include a "drop shadow" border which adds 1 cell on each side (so it increases width and height by 2 each). As you noticed `add_fullscreen_layer` skips this border and should let you have a view that stretches to the border of the terminal.

Regarding `Event::WindowResize`, on the current master branch I am in the process of refactoring a bit the event handling of the cursive root; rather than hard-coding some event responses (like Ctrl-C or WindowResize) it now uses an internal `OnEventView`. In this case, `WindowResize` is configured as a "pre-event". The result is that it prevents both the views and regular callbacks from seeing this event. You will need to use `Cursive::set_on_pre_event()` to register the callback instead.

Regarding the callbacks not being called, I think it might be a problem with the precise view type used. [You seem to wrap the `HideableView` in a `ResizedView`](https://github.com/compenguy/panharmonicon/blob/master/src/terminal.rs#L275).
Having the wrong type in callback is a very common mistake, and I'm thinking of adding debugging tools to inspect the view tree, and ideally print the type of the view with a given name, to help detect this kind of mismatch.

In extreme cases like 1-line terminals, it's possible some views are overly conservative and think they won't fit - I'll have a look and see if we can improve that.

**Comment by gyscos** [comment]
Regarding type mismatch for views, I just added `Cursive::debug_name(&self, name: &str) -> Option<&'static str>` which internally uses [`std::any::type_name()`](https://doc.rust-lang.org/std/any/fn.type_name.html) to return the name of the type of the view. It can help debug cases like that.

**Comment by compenguy** [comment]
Thanks for your work!  Items 1 and 3 are now straightened out (#2 wasn't actually an issue, just context).

For #4, I switched to adding a fullscreen layer, and got it down to one row of dead space.  Hiding the DummyView gets rid of that last row, so apparently the DummyView doesn't like being forced down to 0 rows _ever_.

In any case, I've resolved all my UI scaling issues, and I'm pretty pleased with the result.  Thanks for your support!
