### ISSUE TITLE
[Help] Is there a way to get the _actual_ size of a view

### ISSUE THREAD

**Issue by jansc** [gyscos/cursive#437]
I need some help. I'd like to get the _actual_ size of a view as displayed on the screen.

# Problem description

I have a `SelectView` inside a `ScrollView`, and like to implement pager functionality in the `SelectView`. 
So if the user presses Space, I'd like to scroll down to the next page (or maybe the next page minus one row). To do this, I need to know the number of rows displayed by the `ScrollView`.

Also, if I knew the width of the `ScrollView`, I could implement row wrapping in the underlying `SelectView`.

Is there a way to do this?

# Environment

* Operating system: Linux/FreeBSD
* Backend used: ncurses 5.9
* Current locale
```
LANG=nb_NO.UTF-8
LC_CTYPE="nb_NO.UTF-8"
LC_COLLATE="nb_NO.UTF-8"
LC_TIME="nb_NO.UTF-8"
LC_NUMERIC="nb_NO.UTF-8"
LC_MONETARY="nb_NO.UTF-8"
LC_MESSAGES="nb_NO.UTF-8"
LC_ALL=
```
* Cursive version 0.14.0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I think there's a good chance retrieving the actual size is _not_ what you want here. In particular, instead of having the `SelectView` implement pagination, why not do it in the `ScrollView`? It sounds like a great place to do that, since "scroll down to the next page" is something the `ScrollView` should do, not `SelectView`.

In general, the idea is that anything _inside_ a `ScrollView` is not even aware that it is scrolling. For all it knows, it lives in a giant screen where everything fits easily (though it can be configured to only do that on one axis). This makes it easy to write most views, since you don't have to care about scrolling too much. Otherwise things could get really complex, especially when you start having nested `ScrollView`.

In this case, you would:
* Use `ScrollView::content_viewport` to find what part of the `SelectView` is currently "visible".
* Get the `bottom_left` corner from this viewport.
* Use `ScrollView::set_offset` to jump to this new offset.
* Profit

> Also, if I knew the width of the ScrollView, I could implement row wrapping in the underlying SelectView

Right now `SelectView` is a bit limited and only support 1-line items, so it doesn't support line wrapping at all. But if it did, the solution would be to just disable x-axis scrolling for the `ScrollView`; this way, it will forward the width restriction from the parent, and `SelectView` would be able to line-wrap its content.

**Comment by jansc** [comment]
Thank you for taking the time to write this answer. Works like a charm!
