### ISSUE TITLE
StyledString breaks SelectView highlighting 

### ISSUE THREAD

**Issue by danobi** [gyscos/cursive#481]
> First: is this a bug report? A suggestion? Or asking for help?

Bug

# Problem description

`StyledString`s causes a break in `SelectView` highlighting.

Here's a diff on one of the example programs:
```diff
iff --git a/examples/select.rs b/examples/select.rs
index 7d70021..4e4d57f 100644
--- a/examples/select.rs
+++ b/examples/select.rs
@@ -3,6 +3,8 @@ use cursive::event::EventResult;
 use cursive::traits::*;
 use cursive::views::{Dialog, OnEventView, SelectView, TextView};
 use cursive::Cursive;
+use cursive::utils::markup::StyledString;
+use cursive::theme::{Color, BaseColor};

 // We'll use a SelectView here.
 //
@@ -16,13 +18,10 @@ fn main() {
         // Use keyboard to jump to the pressed letters
         .autojump();

-    // Read the list of cities from separate file, and fill the view with it.
-    // (We include the file at compile-time to avoid runtime read errors.)
     let content = include_str!("../assets/cities.txt");
-    select.add_all_str(content.lines());
-
-    // Sets the callback for when "Enter" is pressed.
-    select.set_on_submit(show_next_window);
+    for line in content.lines() {
+        select.add_item(StyledString::styled(line, Color::Light(BaseColor::Green)), 0);
+    }

     // Let's override the `j` and `k` keys for navigation
     let select = OnEventView::new(select)
@@ -46,13 +45,3 @@ fn main() {

     siv.run();
 }
-
-// Let's put the callback in a separate function to keep it clean,
-// but it's not required.
-fn show_next_window(siv: &mut Cursive, city: &str) {
-    siv.pop_layer();
-    let text = format!("{} is a great city!", city);
-    siv.add_layer(
-        Dialog::around(TextView::new(text)).button("Quit", |s| s.quit()),
-    );
-}
```

Screenshot:
![color highlight](https://user-images.githubusercontent.com/824615/89332814-deab9e80-d648-11ea-9ca5-e63255e4b00d.png)

# Environment

> * Operating system: linux distribution, windows, macOS, ...

fedora 32

> * Backend used: ncurses (the default one), pancurses, termion, ...
>  * If using ncurses on linux, ncurses version? (run `grep "define NCURSES_VERSION " /usr/include/curses.h`)

ncurses:
```
$ grep "define NCURSES_VERSION " /usr/include/curses.h
#define NCURSES_VERSION "6.1"
```

> * Current locale (run `locale` in a terminal).
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

> * Cursive version (from crates.io, from git, ...)

Built from master

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, highlighting and custom styles don't go very well together right now.

There's a few directions we could go.
One idea is to use a "partial style" for highlighting where it only overrides the background but keeps the foreground. 
We could also just apply "reverse" to the row instead of manually setting front/back in `ColorStyle::highlight()`. Moving to using `Style` instead of `ColorStyle` may help with that.

**Comment by danobi** [comment]
> One idea is to use a "partial style" for highlighting where it only overrides the background but keeps the foreground.

Wouldn't that break the `HighlightText` palette option?

> We could also just apply "reverse" to the row instead of manually setting front/back in ColorStyle::highlight()

Same as above, unless you're considering an API change.

--

I haven't looked at the code for this but would it be possible to (logically) apply `StyledString` effects to text after the highlight? It seems sensible to me from an API perspective that when a user uses a `StyledString` they want a very specific effect that overrides the global theme.

**Comment by gyscos** [comment]
> > One idea is to use a "partial style" for highlighting where it only overrides the background but keeps the foreground.
>
> Wouldn't that break the HighlightText palette option?

Ah right, I got it backward: let the text only override the front color, and not the background color, so that it keeps using the "highlight" background. This would be done by using a front-color-only style on the text.
Giving test a style that include a background would still visually conflict with the highlighting around them though.

> > We could also just apply "reverse" to the row instead of manually setting front/back in ColorStyle::highlight()
>
> Same as above, unless you're considering an API change.

Well... conceptually we could split the "highlight" effect in 2 actions:
* Replace the front color from `Primary` (black) to `Highlight` (red) or `HighlightInactive` (blue), and the background color from `View` to `HighlightText` (the same color by default).
* Apply "reverse", so the background is now `Highlight` and the front `HighlightText`.

Only right now we're directly jumping to the final state. Actually separating it in two steps would potentially interact better with styled text, which would override the color change, but still be reversed when highlighted.

**Comment by gyscos** [comment]
With the addition of `ColorType::InheritParent`, color styles can now decide to only override the front or back color. This way we can give a "front-only" style to the select view, and it will correctly be blended with the highlight color.

What we don't do right now is "expand" the style to the padding around the item. Right now even if the user gives a green background, we keep using a red (well, a "Highlight") background for the space around the item. We _could_ peek at the first and last spans in the text, check its background, and if it's not `InheritParent`, use _that_ as the highlight color.
