### ISSUE TITLE
find_name how to use it?

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#484]
```
fn Enter_Fn(siv: &mut cursive::Cursive, row: usize,index: usize)
{
    let v = siv.find_name::<Dialog>(&String::from(format!("a {}",0)));//I CANNOT FIND THAT DIALOG!!!!!!????
    match v 
    {
        Some(vv)=>println!("Some"),
        None=>println!("None")
    }
}

fn main() {

    let mut app = cursive::default();
    let mut horizontalLayout_MainPanels = LinearLayout::new(Orientation::Horizontal);
 
        let mut panel_left = create_table();
        panel_left.set_on_submit(Enter_Fn);
        
        horizontalLayout_MainPanels.add_child(ResizedView::with_full_screen(Dialog::around(panel_left).title(format!("a {}",0))));//**Here I'm creating view and naming it** "a 0"
 

app.run()
}
```
Could you please provide example how to find a view just like I'm trying to do in the code above?
Thanks

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Note that a Dialog's title and a view attached name are different concepts. The title is only the text at the top of the dialog; the name is an invisible value used to retrieve the view.

You can check [the tutorials](https://github.com/gyscos/cursive/blob/main/doc/tutorial_3.md) for how to use named views, including `Cursive::find_name` and `Cursive::call_on_name`, but mainly it involves:

* Import the [`Nameable` trait](https://docs.rs/cursive/0.15.0/cursive/traits/trait.Nameable.html) for easy naming of views: `use cursive::traits::Nameable as _;`
* Use `.with_name()` instead of/in addition to `.title()`.

**Comment by gitatomic** [comment]
Hi, thanks for the help. Will try that.
Best regards!

**Comment by smallB007** [comment]
Thank you very much for your help.
Really appreciate it.

**Comment by gyscos** [comment]
I'll close this for now, feel free to re-open if you have further questions!
