### ISSUE TITLE
How to modify inner state based on user input?

### ISSUE THREAD

**Issue by albert-tomanek** [gyscos/cursive#531]
Help: How to modify inner state based on user input?

# Environment

* Operating system: Ubuntu 18.04
* Backend used: ncurses 6.1
* Current locale: en_US
* Cursive version: latest from git

# Problem Description

I'm writing a file dialog for cursive. It's a view group with an EditView.
Whenever the user types '/', I'd like it to automatically display the contents of the directory they've just typed, which requires updating `self.directory` with the EditView's text and calling some other `self.` methods to update the dialog. This requires access to both the Cursive instance and `self` at the same time.

The first solution I saw for this was to set it as a callback to [`EditView::on_edit`](https://docs.rs/cursive/0.15.0/cursive/views/struct.EditView.html#method.on_edit). Although the callback function does get passed the Cursive instance, it can't access `self`.
The other option I saw was to return my processing code [as a closure from on_event](https://docs.rs/cursive/0.15.0/cursive/view/trait.ViewWrapper.html#method.wrap_on_event) (see code below), however again, although the closure gets access to the Cursive instance, it is unable to capture a reference to `self` as it needs to have a `'static` lifetime.

Are views meant to have an inner state?
What is the correct way of achieving this?
Thanks a bunch!

```rust
struct FileDialog {
	dialog: views::Dialog,

	directory: String,
	filename: String,
}

impl ViewWrapper for FileDialog {

	...

	fn wrap_on_event(&mut self, event: Event) -> EventResult {
		EventResult::Consumed(Some(Callback::from_fn(move |siv: &mut Cursive| {          // error[E0759]: `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
			let entry_text = siv.call_on_name("entry", |view: &mut EditView| {
				view.get_content()
			}).unwrap();

			match event {
				Event::Char('/') => {
					(self.directory, self.filename) = Foo( ... &entry_text ... );
				}
				Event::Key(Backspace) if entry_text.ends_with('/') => {
					(self.directory, self.filename) = Bar( ... &entry_text ... );
				}

				_ => {}
			};

			self.update(siv);	// function updates other parts of view based on newly set `self.directory`
		})))
	}
}
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

As you noticed, having both `&mut Cursive` _and_ `&mut self` at the same time is not easy in general. Most of the time, you'll want to split callbacks in a first step that _only_ uses `&mut self`, then a second step that only uses `&mut Cursive` (but possibly carrying results from the first step).

There are two main ways to work around this:
* Find a way to get from `&mut Cursive` to your view, usually by wrapping your view in a `NamedView` and then querying for it.
* Don't require `&mut Cursive` at all, instead define the callbacks on the group itself. This way you have access to the group, from which you can query each child view individually. For example in your `wrap_on_event`, instead of running `siv.call_on_name("entry", ...)`, you can directly dig into `self.dialog`, for example using `self.dialog.call_on_name("entry", ...")` from the [`Finder`](https://docs.rs/cursive/0.15.0/cursive/traits/trait.Finder.html) trait.

**Comment by albert-tomanek** [comment]
Ahh, I wasn't aware of the Finder trait. That does make things a lot easier. 
Thanks for the advice!
