### ISSUE TITLE
Getting value from EditView always returns Some

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#569]
**Describe the bug**
Get value from edit view using call_on_name. Always returns Some even if EditView has no content. 

**To Reproduce**
Call get_content on EditView, from inside call_on_name

**Expected behavior**
I believe the design could be improved by changing field in EditView content: Rc<String>, to EditView content: Option<Rc<String>>.
That way we would get meaningful answer from get_content, either Some(content) or None if there is no content.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I would say "empty content" is a valid content. As you noticed in https://github.com/gyscos/cursive/pull/570, making it optional brings quite some added complexity to handle the `None` case, while everything works naturally with an empty string.

As for the API, I think it is simpler by just returning access to the content, whether it's been edited or not. _Most of the time_ users don't care if a field is empty because it was left untouched or changed and emptied again (and for those who want that, it's easier to wrap the `EditView` and detect if any event was received).

**Comment by smallB007** [comment]
Fair enough, although even the "perceived" complexity when you think about it avoids unnecessary processing in number of cases where there is no content, but in general, I agree, let's keep things simple.
