### ISSUE TITLE
[FEATURE] Change .find_child_from_name() to return strictly typed views.

### ISSUE THREAD

**Issue by T-O-R-U-S** [gyscos/cursive#595]
**Is your feature request related to a problem? Please describe.**
It's incredibly frustrating when I want to get something from inside of a LinearLayout, and all I can get is an object with a very basic and generic `cursive::View` type. It doesn't at all work for my use-cases, and it's also inconsistent with how `siv.find_name()` functions.

**Describe the solution you'd like**
I advocate for renaming the incredibly verbose `.find_child_from_name()` to something less wordy, as well as using type generics when getting a child by name. In cases where you are simply fetching a child using a `usize`, it would make sense to return a `cursive::View` trait because the order of elements can change at run time, but when fetching using a name, that isn't so much the case.

**Describe alternatives you've considered**
- using `siv.find_name()` doesn't work when an element is inside of a LinearLayout for some reason
- I've search through all of the `LinearLayout` methods on the [docs.rs](https://docs.rs/cursive/0.16.3/cursive/views/struct.LinearLayout.html) page to see if I would find something that fits my needs. I have found nothing.

**Additional context**
I'm trying to set the content of a `text_area`, and since I'm doing it inside of a closure I have to fetch it from the `cursive::CursiveRunnable` instead of directly using a reference to it.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

* `find_name` should totally work with views inside LinearLayout, do you have an example that's not working?
* From a `View` you can get the actual type you need with the downcast class of methods: https://docs.rs/cursive/0.16.3/cursive/view/trait.View.html#method.downcast
* I'm also totally up to renaming methods to something that fits better!

(I'm currently traveling and will have more time to answer a bit later.)

**Comment by T-O-R-U-S** [comment]
Answers to questions (in order)
- Yes, I do :), since Rust (for some reason) doesn't print anything to the terminal when a Cursive app crashes (Not sure if this is Cursive or the backend that Cursive uses... I actually should've opened a ticket about that one, but here I've used `.is_some()` to prove my point)
```rs
use cursive::{
    traits::*,
    views::{
        TextArea,
        LinearLayout,
        Menubar,
        Dialog
    },
    menu::{
        MenuTree
    }
};

fn main() -> anyhow::Result<()> {
    let mut ctx = cursive::default();

    let mut menubar = Menubar::new();

    let mut sub_tree = MenuTree::new();

    sub_tree.add_leaf("Open", |ctx| {
        let text_area = ctx.find_name::<TextArea>("text_area");
        ctx.add_layer(
            Dialog::info(
                // Returns 'false'.
                format!("{}", text_area.is_some())
                // P.S: When Cursive crashes, error messages
                // don't display at all (not printed to terminal)
                // though I'm not sure if this is related to Cursive
                // or your terminal backend.
            )
        )
    });

    sub_tree.add_leaf("New", |ctx| todo!());

    sub_tree.add_leaf("Save", |ctx| todo!());

    menubar.add_subtree("File", sub_tree);

    ctx.add_layer(
        LinearLayout::vertical()
        .child(
            menubar
        )
        .child(
            TextArea::new()
            .full_height()
            .with_name("text_area")
        )
        .with_name("layout")
        .full_width()
    );

    ctx.run();
    Ok(())
}
```
- Thanks for the info! I wasn't aware before, I'll try to implement it into my project later.
- That's good to know 👍🏼. I'm not exactly the best at naming functions/variables, so if more people agree with me about this, then I'm sure the community can agree on a good name for this function.

I'd like to close by thanking you for all the work you do. :)

**Comment by gyscos** [comment]
* Re: invisible error messages: by default, `Cursive` cleans the terminal when the `run` function returns. But the panic happens before that, which means that:
  * When started, cursive sets up the terminal
  * The app panics
  * The panic handler prints an error to stderr
  * The panic rewinds the stack, and eventually drops the `CursiveRunnable`
  * This causes the terminal to be cleaned up, and hides any stderr message

The solution to that is to forward stderr to a file, and check this file separately. [This is mentioned in the doc](https://docs.rs/cursive/0.16.3/cursive/#debugging), but this probably deserves better visibility.

* The issue here is that the `TextArea` is first wrapped in a `ResizedView` (with `.full_height()`), and _then_ given a name - so the `"text_area"` name points at a `ResizedView<TextArea>`, not just a `TextArea`.
It's a common issue, and I try to mention it in [the 3rd tutorial](https://github.com/gyscos/cursive/blob/main/doc/tutorial_3.md), but here again it may benefit from being more prominently warned against.

**Comment by T-O-R-U-S** [comment]
Oh, I see... so it essentially boiled down to me not paying enough attention. Sorry 😅...
