### ISSUE TITLE
Examples do not compile from forked repository

### ISSUE THREAD

**Issue by smallB007** [gyscos/cursive#690]
**Describe the bug**
This is the dependencies section of my Cargo.toml
[dependencies]
#cursive = "*"//Works
cursive = { git = "https://github.com/smallB007/cursive.git" }//Doesn't work, even though it is just a fork
cursive_table_view = { git = "https://github.com/smallB007/cursive_table_view.git" }
rand = "*"

I'm trying to build examples from:
https://github.com/BonsaiDen/cursive_table_view/blob/master/examples/double.rs
But if I use a fork, which I forked and synced I'm getting errors. If I don't use fork but your create it works. Why is that?

The errors (one of many) I'm getting:
error[E0308]: mismatched types
    --> src/main.rs:72:58
     |
72   |         .column(BasicColumn::Count, "Count", |c| c.align(HAlign::Center))
     |                                                    ----- ^^^^^^^^^^^^^^ expected enum `cursive_core::align::HAlign`, found enum `HAlign`

Thank you

[EDIT]
Little extra info, using your git repo also causes those errors, so I believe that you forgot to push something upstream again.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

This issue is not exactly cursive-specific. The problem is that `cursive_table_view` depends on `cursive-core`, which is implicitly the one from crates.io. But the git version of cursive (whether it's from your fork, or even from https://github.com/gyscos/cursive) depends on the git version of cursive-core[^1].
You can check that by running [`cargo tree`](https://crates.io/crates/cargo-tree). On my small example, this results in:
```
% cargo tree | rg cursive  # Only show relevant output, otherwise it will be a bit too big for this answer.
├── cursive v0.20.0 (https://github.com/gyscos/cursive#b84ebdb4)
│   ├── cursive_core v0.3.5 (https://github.com/gyscos/cursive#b84ebdb4)
└── cursive_table_view v0.14.0
    └── cursive_core v0.3.5
```
As you see there are _two_ `cursive_core` versions: one from git, and one from `cursive_table_view`. Rust treats them as completely separate, and will not agree that the `HAlign` type from one is the same as from the other.

So how do we force both crates to be friend and use the same dependency? We can patch that in your example `Cargo.toml`:
```toml
[patch.crates-io]
cursive_core = { git = "https://github.com/gyscos/cursive" }
```

This will ensure that anytime someone wants `cursive-core` from crates.io, it actually uses the one from git. And it works transitively. You can of course use your own fork instead.


[^1]: This happens because the git repository actually contains a workspace with both the `cursive` and the `cursive-core` crates. In that case it appears that cursive uses the `path` dependency for `cursive-core`, rather than the `version` one (which would make it depend on crates.io).

**Comment by smallB007** [comment]
Hello,
Thank you for number of things really! I've learned a lot from your explanation and for that I thank you the most!
