### ISSUE TITLE
[BUG] Limit subview size

### ISSUE THREAD

**Issue by cdxjcl** [gyscos/cursive#775]
**Describe the bug**
I want to limit the size of subviews by wrapping layout method but the result has longer width.

**To Reproduce**

```
let mut siv = cursive::default();
let text = TextView::new("ABCDABCDABCD");
let wrap_view = OnLayoutView::new(
    Layer::new(text),
    |layout, size| {
        layout.layout(Vec2::from((4, 1)));
    },
);
siv.screen_mut().add_transparent_layer(wrap_view);
siv.run();
```

**Expected behavior**
TextView should only display "ABCD".

**Screenshots**

![image](https://github.com/gyscos/cursive/assets/25812821/f40187b1-019a-4986-8c5d-ca3a001f131b)

Expect:
![image](https://github.com/gyscos/cursive/assets/25812821/e7602be1-565f-4482-99c3-fbac5735bc58)

**Environment**
* Operating system used: windows 11
* Backend used: crossterm/blt-backend
* Cursive version: v0.20.0

**Comment by gyscos** [comment]
Hi, and thanks for the report!

To override the size of another view, you actually need to wrap 3 methods:
* The `layout` method, as you did.
* The `required_size` method, which helps the parent view properly center the wrapped view.
* The `draw` method, which crops the printer given to the wrapped view, preventing it from drawing outside of the new size.

The [`ResizedView`](https://docs.rs/cursive/latest/cursive/views/struct.ResizedView.html) [wraps all these](https://docs.rs/cursive_core/latest/src/cursive_core/views/resized_view.rs.html#202-239), and gives you convenient ways to configure what new size the view should have. For example:

```rust
ResizeView::with_fixed_size((4, 1), Layout::new(text))
```
(Other methods exist to only affect the width or height, and to specify min/max values rather than fixed ones.)

With the convenience [`Resizable`](https://docs.rs/cursive/latest/cursive/traits/trait.Resizable.html) trait, you can use chainable methods:
```
Layout::new(text).fixed_size((4, 1))
```
