### ISSUE TITLE
Use Tokio for event loop

### ISSUE THREAD

**Issue by maghoff** [gyscos/Cursive#92]
I am wondering about the need for this project to provide its own event loop. Has there been given any thought into integrating this with [Tokio](https://github.com/tokio-rs/tokio), making Cursive just another thing running on a [tokio-core](https://github.com/tokio-rs/tokio-core)?

As an example use case one can imagine something like aptitude, the ncurses-based front-end to apt. It does a lot of http requests, and it would be nice to be able to do those asynchronously, on the main thread event loop instead of wrangling multiple threads.

While Rust does make it _better_ to wrangle threads, I certainly prefer not to have to, and there is an argument to be made that supporting async with Tokio is strictly more powerful than not :)

I'd love to try an make an attempt at a proof of concept for an integration with Crusive and Tokio if there is interest and I can find the time for it :)

**Comment by matthiasbeyer** [comment]
From my point of view (I do not have knowlegde about the details of tokio or cursive, so take with a grain of salt) no library should implement its own event loop, but let the user provide one.

**Comment by gyscos** [comment]
Cursive's event loop is currently mainly driven by reading from stdin (or from a tty), both blocking, so I'm not sure how easily it can be integrated with tokio.

However, I'm working on pushing this blocking read to another thread, filling a channel instead. That way, the current event loop may gain more freedom (I suspect tokio deals better with channels than with blocking reader - though with my very little knowledge of tokio, I'm really not sure).

As a note, regarding the aptitude example, doing the HTTP calls asynchronously in a single separate thread is probably an easy and efficient solution for now.

**Comment by maghoff** [comment]
Thanks for getting back to me.

The idea would be to change Cursive read from stdin in a non-blocking fashion. There is no underlying technical reason to use threads here. For an example of a rust project that uses stdio with Tokio, see <https://github.com/dpc/async-readline>.

Regarding your note, yes, you only need one additional thread to do any number of asynchronous tasks. The question I am posing is "can we make it zero additional threads?" or "can we make it so Cursive doesn't _force_ the use of an additional thread?"

**Comment by gyscos** [comment]
I see, this one directly uses the stdio file descriptors rather than the std lib's wrappers.

Cursive relies on separate backends to handle the input.
* The original backend, `ncurses`, uses the C `getch()` method. [It looks like there are options to do async read](http://keyvanfatehi.com/2011/08/02/Asynchronous-c-programs-an-event-loop-and-ncurses/), may need some investigations.
* The `pancurses` backend is an abstraction over either `ncurses` on unix or `pdcurses` on windows. Not sure how easily it would be for them to provide a unified tokio-compatible interface.
* [`termion`](https://github.com/ticki/termion), a promising pure-rust backend, also doesn't currently provide a tokio API.
* The [`BearLibTerminal`](https://github.com/nabijaczleweli/BearLibTerminal.rs) is another binding to a C library, which I doubt currently offer async input.

Having a full end-to-end async solution based on tokio looks like a lot of work in many different libraries, for little actual gains (the extra thread required for blocking read is more a problem with the elegance of the solution than an actual technical performance issue).
I'm all for providing a nicer API for various use-cases, so if these libraries end up offering a proper API, I'd be glad to use an async system. And in the meantime, there may be ways to "hide" the ugly blocking low-level, through a channel or whatnot.

**Comment by maghoff** [comment]
Alright, thanks for the detailed follow-up. It seems like waiting for an appropriate backend to appear elsewhere is the right way to go.

Closing this issue now, as I feel I have gotten a satisfactory answer to my question.
